#!/bin/bash
#
# Given a repo and a list of packages, go download the latest matching deb
#

set -e

ARCH="$1"
shift

REPO="$1"
shift

OUTDIR="$1"
shift

if [ -z "$ARCH" -o -z "$REPO" -o -z "$OUTDIR" -o -z "$1" ]; then
    echo "Usage: $0 arch repo unpackdir pkg..."
    exit 1
fi

if [ -z "$TOP_DIR" ]; then
    echo "Need env TOP_DIR set"
    exit 1
fi

if [ ! -r "$TOP_DIR/apt.sources/$REPO.conf" ]; then
    echo "No definition found for repo called $REPO"
    exit 1
fi

. "$TOP_DIR/apt.sources/$REPO.conf"
if [ -z "$REPO_KEY" -o -z "$REPO_SRC" ]; then
    echo "repo definition file did not define correct vars"
    exit 1
fi

mkdir -p "$OUTDIR"
cd  "$OUTDIR"

TMP=./meta
#rm -rf "$TMP"
mkdir -p "$TMP"

mkdir -p $TMP/etc/apt/sources.list.d
echo "$REPO_SRC" >$TMP/etc/apt/sources.list.d/repo.list

TRUSTED=$TMP/etc/apt/trusted.gpg
# It would be nice to fill the keyring..

TRUSTED_PARTS=${TRUSTED}.d/
mkdir -p $TRUSTED_PARTS

ETC=$TMP/etc/apt
mkdir -p $ETC
ETC_PARTS=$ETC/apt.conf.d/
mkdir -p $ETC_PARTS

ETC_PREFS_PARTS=$ETC/preferences.d/
mkdir -p $ETC_PREFS_PARTS

STATE=$TMP/var/lib/apt/
mkdir -p $STATE

STATUS=$TMP/var/lib/dpkg/status
mkdir -p "$(dirname $STATUS)"
touch $STATUS

CACHE=$TMP/var/cache/apt
mkdir -p $CACHE

export APT_CONFIG=$TMP/apt_config
cat >$APT_CONFIG <<EOF
Dir::Etc "$ETC";
Dir::Etc::Parts "$ETC_PARTS";
Dir::Etc::PreferencesParts "$ETC_PREFS_PARTS";
EOF

# provide some trust
if [ "$REPO_KEY" == 'system_trust' ]; then
    # use the current system for trust files
    cp /etc/apt/trusted.gpg ${TRUSTED}
    cp /etc/apt/trusted.gpg.d/* ${TRUSTED_PARTS}
else
    wget -O "${TRUSTED_PARTS}/repo.key.asc" "$REPO_KEY"
fi

#    -o APT::Default-Release='*' \
APT_OPTS="\
    -o Apt::Architecture=$ARCH \
    -o Apt::Get::AllowUnauthenticated=true \
    -o Apt::Get::Download-Only=true \
    -o Apt::Install-Recommends=false \
    -o Dir::Etc::TrustedParts=$TRUSTED_PARTS \
    -o Dir::Etc::Trusted=$TRUSTED \
    -o Dir=$TMP \
    -o Dir::Etc=$ETC \
    -o Dir::Etc::Parts=$ETC_PARTS \
    -o Dir::Etc::PreferencesParts=$ETC_PREFS_PARTS \
    -o Dir::State=$STATE \
    -o Dir::State::Status=$STATUS \
    -o Dir::Cache=$CACHE \
"

apt-get $APT_OPTS update

apt-get $APT_OPTS --print-uris download "$@" >print_uris.txt

while read URI DEB SIZE HASH; do
    # if the URI is empty, dont try to download anything
    if [ -z "$URI" ]; then
        continue
    fi

    wget -O "${DEB}.tmp" $(echo "$URI" |tr -d "'")
    if [ $? -ne 0 ]; then
        echo bad wget
        exit 1
    fi
    # TODO
    # - check size and hash
    mv "${DEB}.tmp" "${DEB}"

    dpkg -x "$DEB" ./
    if [ $? -ne 0 ]; then
        echo bad dpkg extract
        exit 1
    fi
done <print_uris.txt

